### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lemon-tree007** [johlanse/study_xxqg#124]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37

### 运行环境

CentOS

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

centos安装docker后，定时任务设置，提示invalid memory address or nil pointer dereference，点击开始学习正常运行

### 期望的结果是什么？

定时学习qg

### 实际的结果是什么？

到定时点提示invalid memory address or nil pointer dereference，无法继续运行

### 日志记录（可选）

```golang
2022-10-27T03:31:48.861747000Z [2022-10-27 11:31:48] [info] db_sha: d6e455f03b419af108cced07ea1d17f8268400ad1b6d80cb75d58e952a5609bf
2022-10-27T03:31:48.861970000Z [2022-10-27 11:31:48] [info] 当前程序运行版本： v1.0.37-beta2-SNAPSHOT-39fff30
2022-10-27T03:31:48.862133000Z [2022-10-27 11:31:48] [info] 正在检查更新.
2022-10-27T03:31:48.862304000Z [2022-10-27 11:31:48] [info] 已配置钉钉推送
2022-10-27T03:31:48.862465000Z [2022-10-27 11:31:48] [info] 已开启web配置，web监听地址 ==> 0.0.0.0:8080
2022-10-27T03:31:48.862619000Z [2022-10-27 11:31:48] [info] 已采用定时执行模式
2022-10-27T03:31:49.112545000Z [2022-10-27 11:31:49] [info] 检查更新完成. 当前已运行最新版本.
2022-10-27T03:32:00.002512000Z [2022-10-27 11:32:00] [info] 即将开始执行定时任务
2022-10-27T03:32:00.003422000Z [2022-10-27 11:32:00] [info] 检测到模式 3
2022-10-27T03:32:00.004261000Z [2022-10-27 11:32:00] [info] 已配置钉钉推送
2022-10-27T03:32:00.365841000Z panic: runtime error: invalid memory address or nil pointer dereference
2022-10-27T03:32:00.366712000Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb43174]
2022-10-27T03:32:00.368351000Z goroutine 26 [running]:
2022-10-27T03:32:00.369198000Z main.do({0xc85f16, 0x4})
2022-10-27T03:32:00.369908000Z 	github.com/johlanse/study_xxqg/main.go:234 +0x134
2022-10-27T03:32:00.370496000Z time="2022-10-27T11:32:00+08:00" level=info msg="exit status 2"
2022-10-27T03:32:00.370694000Z main.main.func2.1()
2022-10-27T03:32:00.370884000Z 	github.com/johlanse/study_xxqg/main.go:185 +0x188
2022-10-27T03:32:00.371074000Z github.com/robfig/cron/v3.FuncJob.Run(0x0?)
2022-10-27T03:32:00.371268000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
2022-10-27T03:32:00.371454000Z github.com/robfig/cron/v3.(*Cron).startJob.func1()
2022-10-27T03:32:00.371641000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
2022-10-27T03:32:00.371827000Z created by github.com/robfig/cron/v3.(*Cron).startJob
2022-10-27T03:32:00.372017000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xad
```

**Comment by lemon-tree007** [comment]
docker已更新到新版本，报错依旧

**Comment by lemon-tree007** [comment]
2022-11-02T03:39:51.008236000Z [2022-11-02 11:39:51] [info] db_sha: d6e455f03b419af108cced07ea1d17f8268400ad1b6d80cb75d58e952a5609bf
2022-11-02T03:39:51.008404000Z [2022-11-02 11:39:51] [info] 当前程序运行版本： v1.0.38-SNAPSHOT-4d7b858
2022-11-02T03:39:51.008560000Z [2022-11-02 11:39:51] [info] 正在检查更新.
2022-11-02T03:39:51.009145000Z [2022-11-02 11:39:51] [info] 已配置钉钉推送
2022-11-02T03:39:51.009318000Z [2022-11-02 11:39:51] [info] 已开启web配置，web监听地址 ==> 0.0.0.0:8080
2022-11-02T03:39:51.009493000Z [2022-11-02 11:39:51] [info] 已采用定时执行模式
2022-11-02T03:39:51.274576000Z [2022-11-02 11:39:51] [info] 检查更新完成. 当前已运行最新版本.
2022-11-02T03:41:00.002485000Z [2022-11-02 11:41:00] [info] 即将开始执行定时任务
2022-11-02T03:41:00.003213000Z [2022-11-02 11:41:00] [info] 检测到模式 3
2022-11-02T03:41:00.003883000Z [2022-11-02 11:41:00] [info] 已配置钉钉推送
2022-11-02T03:41:01.226240000Z panic: runtime error: invalid memory address or nil pointer dereference
2022-11-02T03:41:01.226703000Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb2e7a2]
2022-11-02T03:41:01.227091000Z goroutine 74 [running]:
2022-11-02T03:41:01.227271000Z github.com/panjf2000/ants/v2.(*PoolWithFunc).Invoke(0xc0005e0510?, {0xb77b40?, 0xc000726450?})
2022-11-02T03:41:01.227452000Z 	github.com/panjf2000/ants/v2@v2.5.0/pool_func.go:184 +0x22
2022-11-02T03:41:01.227603000Z main.run(...)
2022-11-02T03:41:01.227753000Z 	github.com/johlanse/study_xxqg/run.go:26
2022-11-02T03:41:01.227907000Z main.do()
2022-11-02T03:41:01.228057000Z 	github.com/johlanse/study_xxqg/main.go:262 +0x25e
2022-11-02T03:41:01.228215000Z main.main.func2.1()
2022-11-02T03:41:01.228374000Z 	github.com/johlanse/study_xxqg/main.go:187 +0x17c
2022-11-02T03:41:01.228524000Z github.com/robfig/cron/v3.FuncJob.Run(0x0?)
2022-11-02T03:41:01.228675000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
2022-11-02T03:41:01.228825000Z github.com/robfig/cron/v3.(*Cron).startJob.func1()
2022-11-02T03:41:01.228976000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
2022-11-02T03:41:01.229129000Z created by github.com/robfig/cron/v3.(*Cron).startJob
2022-11-02T03:41:01.229284000Z 	github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xad
2022-11-02T03:41:01.230848000Z time="2022-11-02T11:41:01+08:00" level=info msg="exit status 2"
